#pragma once

enum GrassTile_t {
	GT_DIRT = 0,
	//single row platforms
	GT_SINGLE_ROW_LEFT,
	GT_SINGLE_ROW_MIDDLE,
	GT_SINGLE_ROW_RIGHT,
	//multi-row platforms
	GT_MULTI_LEFT_BOTTOM,
	GT_MULTI_RIGHT_BOTTOM,
	GT_MULTI_MIDDLE_BOTTOM,
	GT_MULTI_LEFT_TOP,
	GT_MULTI_RIGHT_TOP,
	GT_MULTI_MIDDLE_TOP,
	GT_MULTI_LEFT,
	GT_MULTI_RIGHT,

	//corner
	GT_CORNER_TOP_LEFT,
	GT_CORNER_TOP_RIGHT,
	GT_CORNER_BOTTOM_LEFT,
	GT_CORNER_BOTTOM_RIGHT,

	GT_MAX,
};